### ISSUE TITLE
Upgrade Selenium Server 2.0 beta 1 (to fix e.g. `Delete All Cookies`)

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#160]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160) by jollych... on 12 Dec 2010_

“Delete All Cookies” doesn't works
## as the selenium_server_log.txt  display,this keyword works fine

13:42:11.701 INFO - Command request: deleteAllVisibleCookies[, ] on session b85cc414d7fa47f88e61ecd4be4ff438
## 13:42:11.739 INFO - Got result: OK on session b85cc414d7fa47f88e61ecd4be4ff438

Actually ,all the cookies doesn't delete 
My environment details:
Robot Framework 2.5.4 (Python 2.6.1 on darwin)
Seleniumlibrary 2.5
Firefox 3.6.12@&#8288;Mac OS 10.6.5

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c1) by jollych... on 12 Dec 2010_

Selenium RC server version is 2.0a7

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c2) by @pekkaklarck on 13 Dec 2010_

How did you verify that the cookies weren't deleted? Have you looked at Selenium's tracker is something similar submitted there? This would be a Selenium bug anyway and we cannot do much for it other than adding a note to the keyword that it doesn't always work.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c3) by @pekkaklarck on 13 Jan 2011_

jollychang, do you have any more information about this issue?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c5) by jollych... on 17 Jan 2011_

I Think this issue be fixed in Selenium RC Server 2.0b1

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c6) by @pekkaklarck on 19 Jan 2011_

So this is Seleniun bug? Has a version with the fix been released already?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c7) by jollych... on 19 Jan 2011_

yes ,Selenium's bug,2.0b1 fixed that

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c8) by @pekkaklarck on 19 Jan 2011_

We seem to distribute Selenium RFC 1.0.3 with this library. I believe this version is already based on Selenium 2 so we could possibly switch to 2.0b1. Have you jollych... tested SeleniumLibrary with that version?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c9) by @pekkaklarck on 27 Jan 2011_

We have updated Selenium Server included with the library to 2.0 beta 1. Notice that we still use the Selenium 1.0 RC API and not the new WebDriver based API.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c10) by sumit.mo... on 1 Feb 2012_

Hi,

Delete All Cookies still not working with robotframework Selenium2Library 0.5.2.
Keyword run successfully, doesn't give any error.However, cookies not deleted from browser.
Please let me know if there is any fix availble.

Robotframework - 2.6.3
Python 2.7

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c11) by pushkar.... on 21 Nov 2014_

Is "Delete All Cookies" issue resolved? It is still not working

Robot Framework 2.8.6 (Python 2.7.6 on linux2)

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=160#c12) by filiceal... on 10 Jul 2015_

Delete All Cookies still seems to be broken

**Comment by evenicoulddoit** [comment]
@spooning did anything come of this?

**Comment by pekkaklarck** [comment]
I don't remember which Selenium Server version was included in the latest SeleniumLibrary versions. Please check the version included in 2.9.2 release.

Notice that this library is deprecated and all users should migrate to Selenium2Library. There are not going to be any new releases anymore.
