### ISSUE TITLE
Mistype in JVM option documentation for Start Selenium Server keyword

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#255]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=255) by andrey.hitrin on 26 Dec 2012_

There is some difference between project documentation and actual code in the Selenium Library 2.9.1.

An example in documentation says:

&gt; Start Selenium Server  | -JVM=-DserverName=somehost | # Define JVM options.    

But, actually, this example is incorrect. "JVM" option must be used without leading dash.

I've attached a patch with fix for this problem.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=255#c1) by @pekkaklarck on 11 Jan 2013_

Good catch. If we ever have more SeLib releases this will definitely be included.

**Comment by pekkaklarck** [comment]
Fixed in 1194f5ef92ee2bd49ac830e6698db0463b5a193c.
