### ISSUE TITLE
Support Safari

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#257]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=257) by frankbp on 24 Apr 2013_

the 1.1 release does not have the support for Safari (in Windows)

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=257#c1) by @jussimalinen on 13 Aug 2015_

We are moving Selenium Library to github and creating a last release with Robot 2.9 support before stopping the support of this project entirely.

We will update the included SeleniumLibrary and will support the browsers that it will support. Safari should be supported.

**Comment by jussimalinen** [comment]
After updating the latest Selenium Server Safari did not work out of the box. It could be possible to make it work (perhaps), but as this project is deprecated, those who need Safari should move to Selenium2Library.
