### ISSUE TITLE
Patch for /src/SeleniumLibrary/screenshot.py

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#262]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=262) by jollych... on 17 Jul 2013_

screenshot file name append hash, for selenium grid2 runner report

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=262#c1) by jollych... on 25 Jul 2013_

anybody can merge it?thanks

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=262#c2) by @jussimalinen on 13 Aug 2015_

We are moving Selenium Library to github and creating a last release with Robot 2.9 support before stopping the support of this project entirely.

We will look at merging the patch before creating the last release.

**Comment by pekkaklarck** [comment]
Attachment cannot be copied from Google Code so here's the proposed patch:

``` diff
--- a/src/SeleniumLibrary/screenshot.py
+++ b/src/SeleniumLibrary/screenshot.py
@@ -80,6 +80,8 @@
             filename = self._namegen.next()
         else:
             filename = filename.replace('/', os.sep)
+        import os
+        filename = filename.replace('.png', '%s.png' % os.urandom(16).encode('hex'))
         logdir = self._get_log_dir()
         path = os.path.join(logdir, filename)
         link = utils.get_link_path(path, logdir)
```

**Comment by pekkaklarck** [comment]
We decided not to do the proposed change because it would change behavior in backwards incompatible manner. It could be considered in a major version, but because this library is deprecated we are not planning to release new major versions.
