### ISSUE TITLE
Compatibility issue with latest Mozilla Firefox versions

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#268]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=268) by srin... on 6 Aug 2014_

Hi,

We are trying to run few ROBOT selenium test cases on RHEL 7. It seems robotframework-seleniumlibrary-2.9.1 not compatible with Firefox version 24.4.0. The page loading is not happening properly. I have tried the same URL on firefox manually. There is no issue observed.

The test cases are failing with below error. 

14:33:45.366 INFO - Command request: click[xpath=//input[@&#8288;id="logon" or @&#8288;name="logon" or @&#8288;value="logon" or @&#8288;src="logon" or @&#8288;src="http://127.0.0.1:12321/logon" ] on session facabf43bd1a40fa948883811f610120
14:33:45.385 INFO - Got result: ERROR: Invalid xpath [2]: //input[@&#8288;id="logon" or @&#8288;name="logon" or @&#8288;value="logon" or @&#8288;src="logon" or @&#8288;src="http://127.0.0.1:12321/logon" on session facabf43bd1a40fa948883811f610120

The same testcase was passing on Mozilla Firefox 3.6.24 and RHEL 6.2

I am attaching the screenshots for manual, selenium and selenium_server_log for your reference. Please let me know if you need any further traces to analyze this issue. 

Regards,
Srini.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=268#c1) by @jussimalinen on 13 Aug 2015_

We are moving Selenium Library to github and creating a last release with Robot 2.9 support before stopping the support of this project entirely.

We will update the included Selenium Server and we will support the browsers supported by it.

**Comment by jussimalinen** [comment]
Fixed by updating the Selenium Server in 4f23d2b32a3453ce0e243b55fcc47d723a53a5e2
