### ISSUE TITLE
Not working with Firefox 35

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#270]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=270) by priya.... on 10 Mar 2015_

Observed in Robot-framework automation for flash , SeleniumLibrary is not supporting Firefox 35

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=270#c1) by @pekkaklarck on 13 Aug 2015_

First of all, this library has never supported Flash, only Flex. We'll move this library to GitHub and create one more release with updated Selenium server. I'll leave this issue open as a reminder to test that Flex still works in general.

**Comment by jussimalinen** [comment]
Fixed by updating Selenium Server in 4f23d2b32a3453ce0e243b55fcc47d723a53a5e2

**Comment by pekkaklarck** [comment]
This is essentially a duplicate of #268.
