### ISSUE TITLE
Incompatibility with Robot Framework 2.9

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#273]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=273) by vadym.vikulin on 7 Aug 2015_

Environment: jython 2.7rc3

The issue occurs for selenium RC1 library v2.9.1:
Error in file '/data/edtest/resource/setup.txt': Importing test library 'SeleniumLibrary' failed: ImportError: cannot import name GLOBAL_VARIABLES
Traceback (most recent call last):
File "/usr/jython-2.7-rc3/Lib/site-packages/SeleniumLibrary/init.py", line 24, in
from robot.variables import GLOBAL_VARIABLE

**Comment by pekkaklarck** [comment]
I was slightly worried that `BuiltIn.get_variables` that the code now uses would have been added in a somew recently making SeLib incompatible with a bit older releases. It turned out that it was added already in RF 2.1.3 so I would say we are safe.
