### ISSUE TITLE
robotframework/ resource not located

### ISSUE THREAD

**Issue by SaurabhNain** [robotframework/OldSeleniumLibrary#274]
Sending a Post call with '/api/v1/generate' as endpoint Passes with 201 created.
Same call with '/api/v2/generate' or '/api/v3/generate' as endpoint Fails with 404 Not Found.
Rest of the parameters are same. 
I am facing this issue in Robot Framework. All those 3 calls passes manually, via Postman.
What could be the issue here?

**Comment by pekkaklarck** [comment]
This issue has nothing to do with this library.
