### ISSUE TITLE
Cannot slect and test Modal Dialogues. When popup test is frozen

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#9]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=9) by m.marag... on 12 Oct 2008_

**What steps will reproduce the problem?**
1. Try to use a page that will display a popup window. i.e an
authentication dialogue
2. Cannot select it and enter the required info , thus test is stack...
**3.**

**What is the expected output? What do you see instead?**
Should be able to select the popup and enter required info and submit it

**What version of the product are you using? On what operating system?**
Robot framework 2.02 with latest selenium on ubuntu 8.04 or RHEL 4.6

**Please provide any additional information below.**

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=9#c2) by @yanne on 14 Oct 2008_

Implemented 'Select Window' keyword in <a href="https://code.google.com/p/robotframework-seleniumlibrary/source/detail?r=58">r58</a>.
This keyword is able to select the popup window.

**Comment by Jibin1995** [comment]
I was trying to interact with modal popup window and tried with Switch window and Select window...still the elements are not interactable....can someone help me ?
